spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/database
    username: postgres
    password: qny47bsq
  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml
    enabled: true


